import 'package:plugin_platform_interface/plugin_platform_interface.dart';

import 'channel_danfoss_api_wrapper.dart';

/// The interface that implementations of danfoss_api_wrapper must implement.
abstract class DanfossApiWrapperPlatform extends PlatformInterface {
  static final Object _token = Object();

  static DanfossApiWrapperPlatform _instance = ChannelDanfossApiWrapper();

  /// Constructor.
  DanfossApiWrapperPlatform() : super(token: _token);

  /// The default instance of [DanfossApiWrapperPlatform] to use.
  /// Defaults to [ChannelDanfossApiWrapper].
  static DanfossApiWrapperPlatform get instance => _instance;

  /// Platform-specific plugins should set this with their own platform-specific
  /// class that extends [DanfossApiWrapperPlatform] when they
  /// register themselves.
  static set instance(DanfossApiWrapperPlatform instance) {
    PlatformInterface.verifyToken(instance, _token);
    _instance = instance;
  }

  /// Initializes the Danfoss Plus+1 System API.
  ///
  /// Returns true if correctly initialized, false otherwise.
  Future<bool> initialize() {
    throw UnimplementedError('initialize() has not been implemented.');
  }

  /// Sends the request to the Danfoss Plus+1 System API.
  ///
  /// [jsonRequest] the request in json format as string.
  ///
  /// Returns the response in json format as string, null if the no response is
  /// generated by the API. The returned future completes with an error if there
  /// are any communication problems with the API.
  Future<String?> callService(String jsonRequest) {
    throw UnimplementedError('call_service() has not been implemented.');
  }

  /// Stream used to recive callbacks from the Danfoss Plus+1 System API.
  /// It must be a broadcast stream since it is splitted in message-specific
  /// streams by danfoss_api_wrapper package.
  Stream<String> get callbackStream {
    throw UnimplementedError('callback() has not been implemented.');
  }
}
